spring:
  application:
    name: spring-ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llava
          keep_alive: 30m

gpt4all:
  options:
    model-file-path: ../gpt4all_models/ggml-model-gpt4all-falcon-q4_0.bin
